### ISSUE TITLE
I need someone to make a change

### ISSUE THREAD

**Issue by stevenklassen8376** [stevenklassen8376/refactored-guide#2]
I want to test someone making a change. Specifically I want to know:

1. People cannot just push changes to the master branch.
2. People can push their branches and create a pull request.
3. People can comment on/create the issues.

**Comment by Arunass** [comment]
I made one.  But github won't let me push.  I wonder whether you really want to allow any-old-body to push changes.  I think the idea is that people fork your project, modify it and then send you a pull request or something like that - then you can pick what you want to include in your results

**Comment by stevenklassen8376** [comment]
Ok, this test worked (you can comment on issues).
